### ISSUE TITLE
Request to Share Pre-trained Model

### ISSUE THREAD

**Issue by Tangkexian** [mckellwoodland/fid-med-eval#1]
Hi, I'm interested in your project and the work you've done with the pre-trained model. I was wondering if there are any plans to make the model publicly available for use by the community? It could be a valuable resource for others working on similar projects, and I would greatly appreciate it if you could consider sharing it.
Thank you for your time and consideration.

**Comment by mckellwoodland** [comment]
Hello!

Thank you for your interest and kind words. For right now, I'm happy to respond to individual requests for specific models. You may email me at mjs32@rice.edu or mewoodland@mdanderson.org. Please identify the dataset and data augmentation method for the models you are interested in. Please also specify if you'd like the weights at the end of training (which were used for the paper) or the weights associated with the best ImageNet-based FID.

In the future, I do hope to release weights publicly.

McKell
